# Default values for arturonet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

website:
  name: arturonet-website
  replicas: 2
  image:
    repository: arturoguerra/arturonet
    pullPolicy: IfNotPresent
    tag: 77e8ac9ac761b8f7e9308403ae63add9d6c2b4b8
  config:
    BASE_URL: "http://arturonet-api/api"
    BROWSER_BASE_URL: "https://arturonet.com/api"
api:
  name: arturonet-api
  replicas: 2
  image:
    repository: arturoguerra/arturonet-api
    pullPolicy: IfNotPresent
    tag: 975249e22d0cd08168d31ce431a950deab853b82
  config: {}
tls:
  enabled: true
ingress:
  name: arturonet
  host: arturonet.com
  paths:
    - path: "/api/"
      port: 80
      service: arturonet-api
    - path: "/"
      port: 80
      service: arturonet-website
