# Default values for arturonet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


website:
  name: arturonet-website
  replicas: 2
  image:
    repository: arturoguerra/arturonet
    pullPolicy: IfNotPresent
    tag: latest
website:
  name: arturonet-api
  replicas: 2
  image:
    repository: arturoguerra/arturonet-api
    pullPolicy: IfNotPresent
    tag: latest

tls:
  enabled: true

ingress:
  name: arturonet
  host: arturonet.com
  paths:
    - path: "/api/"
      port: 80
      service: arturonet-api
    - path: "/"
      port: 80
      service: arturonet-website
