# Default values for arturonet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

website:
  name: website
  replicas: 2
  image:
    repository: arturoguerra/arturonet
    pullPolicy: IfNotPresent
    tag: 1b88a45936aae24c50b80833461ac8d242bb6a49
tls:
  enabled: true
ingress:
  name: arturonet
  host: arturonet.com
  paths:
    - path: "/"
      service: website
      port: 80
